const BIBLE_VERSES = [
  { verse: "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.", reference: "John 3:16" },
  { verse: "I can do all this through him who gives me strength.", reference: "Philippians 4:13" },
  { verse: "Trust in the LORD with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.", reference: "Proverbs 3:5-6" },
  { verse: "The LORD is my shepherd, I lack nothing.", reference: "Psalm 23:1" },
  { verse: "Be strong and courageous. Do not be afraid; do not be discouraged, for the LORD your God will be with you wherever you go.", reference: "Joshua 1:9" },
  { verse: "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", reference: "Romans 8:28" },
  { verse: "Come to me, all you who are weary and burdened, and I will give you rest.", reference: "Matthew 11:28" },
  { verse: "The LORD is my light and my salvation—whom shall I fear? The LORD is the stronghold of my life—of whom shall I be afraid?", reference: "Psalm 27:1" },
  { verse: "But those who hope in the LORD will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.", reference: "Isaiah 40:31" },
  { verse: "For I know the plans I have for you, declares the LORD, plans to prosper you and not to harm you, plans to give you hope and a future.", reference: "Jeremiah 29:11" },
  { verse: "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God.", reference: "Philippians 4:6" },
  { verse: "The LORD your God is with you, the Mighty Warrior who saves. He will take great delight in you; in his love he will no longer rebuke you, but will rejoice over you with singing.", reference: "Zephaniah 3:17" },
  { verse: "I have told you these things, so that in me you may have peace. In this world you will have trouble. But take heart! I have overcome the world.", reference: "John 16:33" },
  { verse: "So do not fear, for I am with you; do not be dismayed, for I am your God. I will strengthen you and help you; I will uphold you with my righteous right hand.", reference: "Isaiah 41:10" },
  { verse: "The name of the LORD is a fortified tower; the righteous run to it and are safe.", reference: "Proverbs 18:10" },
  { verse: "Cast all your anxiety on him because he cares for you.", reference: "1 Peter 5:7" },
  { verse: "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control.", reference: "Galatians 5:22-23" },
  { verse: "No weapon forged against you will prevail, and you will refute every tongue that accuses you.", reference: "Isaiah 54:17" },
  { verse: "Delight yourself in the LORD, and he will give you the desires of your heart.", reference: "Psalm 37:4" },
  { verse: "Be still, and know that I am God.", reference: "Psalm 46:10" },
  { verse: "The LORD is close to the brokenhearted and saves those who are crushed in spirit.", reference: "Psalm 34:18" },
  { verse: "If God is for us, who can be against us?", reference: "Romans 8:31" },
  { verse: "For where two or three gather in my name, there am I with them.", reference: "Matthew 18:20" },
  { verse: "Love is patient, love is kind. It does not envy, it does not boast, it is not proud.", reference: "1 Corinthians 13:4" },
  { verse: "Therefore, if anyone is in Christ, the new creation has come: The old has gone, the new is here!", reference: "2 Corinthians 5:17" },
  { verse: "Jesus said to her, 'I am the resurrection and the life. The one who believes in me will live, even though they die.'", reference: "John 11:25" },
  { verse: "He has made everything beautiful in its time. He has also set eternity in the human heart.", reference: "Ecclesiastes 3:11" },
  { verse: "The steadfast love of the LORD never ceases; his mercies never come to an end; they are new every morning; great is your faithfulness.", reference: "Lamentations 3:22-23" },
  { verse: "In the beginning God created the heavens and the earth.", reference: "Genesis 1:1" },
  { verse: "Create in me a pure heart, O God, and renew a steadfast spirit within me.", reference: "Psalm 51:10" },
  { verse: "Blessed are the peacemakers, for they will be called children of God.", reference: "Matthew 5:9" },
  { verse: "The LORD bless you and keep you; the LORD make his face shine on you and be gracious to you.", reference: "Numbers 6:24-25" },
  { verse: "I sought the LORD, and he answered me; he delivered me from all my fears.", reference: "Psalm 34:4" },
  { verse: "For the wages of sin is death, but the gift of God is eternal life in Christ Jesus our Lord.", reference: "Romans 6:23" },
  { verse: "Do everything in love.", reference: "1 Corinthians 16:14" },
  { verse: "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.", reference: "John 14:27" },
  { verse: "He gives strength to the weary and increases the power of the weak.", reference: "Isaiah 40:29" },
  { verse: "Be kind and compassionate to one another, forgiving each other, just as in Christ God forgave you.", reference: "Ephesians 4:32" },
  { verse: "The grass withers and the flowers fall, but the word of our God endures forever.", reference: "Isaiah 40:8" },
  { verse: "Jesus answered, 'I am the way and the truth and the life. No one comes to the Father except through me.'", reference: "John 14:6" },
  { verse: "For it is by grace you have been saved, through faith—and this is not from yourselves, it is the gift of God.", reference: "Ephesians 2:8" },
  { verse: "Wait for the LORD; be strong and take heart and wait for the LORD.", reference: "Psalm 27:14" },
  { verse: "The LORD is my rock, my fortress and my deliverer; my God is my rock, in whom I take refuge.", reference: "Psalm 18:2" },
  { verse: "Above all, love each other deeply, because love covers over a multitude of sins.", reference: "1 Peter 4:8" },
  { verse: "See what great love the Father has lavished on us, that we should be called children of God!", reference: "1 John 3:1" },
  { verse: "Your word is a lamp for my feet, a light on my path.", reference: "Psalm 119:105" },
  { verse: "In their hearts humans plan their course, but the LORD establishes their steps.", reference: "Proverbs 16:9" },
  { verse: "Guard your heart above all else, for it determines the course of your life.", reference: "Proverbs 4:23" },
  { verse: "He heals the brokenhearted and binds up their wounds.", reference: "Psalm 147:3" },
  { verse: "And now these three remain: faith, hope and love. But the greatest of these is love.", reference: "1 Corinthians 13:13" },
  { verse: "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.", reference: "Galatians 6:9" },
  { verse: "The LORD himself goes before you and will be with you; he will never leave you nor forsake you. Do not be afraid; do not be discouraged.", reference: "Deuteronomy 31:8" },
  { verse: "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", reference: "Matthew 6:33" },
  { verse: "Consider it pure joy, my brothers and sisters, whenever you face trials of many kinds, because you know that the testing of your faith produces perseverance.", reference: "James 1:2-3" },
  { verse: "Every good and perfect gift is from above, coming down from the Father of the heavenly lights.", reference: "James 1:17" },
  { verse: "This is the day the LORD has made; let us rejoice and be glad in it.", reference: "Psalm 118:24" },
  { verse: "He who began a good work in you will carry it on to completion until the day of Christ Jesus.", reference: "Philippians 1:6" },
  { verse: "You are the light of the world. A town built on a hill cannot be hidden.", reference: "Matthew 5:14" },
  { verse: "I will instruct you and teach you in the way you should go; I will counsel you with my loving eye on you.", reference: "Psalm 32:8" },
  { verse: "As iron sharpens iron, so one person sharpens another.", reference: "Proverbs 27:17" },
  { verse: "For God gave us a spirit not of fear but of power and love and self-control.", reference: "2 Timothy 1:7" },
  { verse: "The joy of the LORD is your strength.", reference: "Nehemiah 8:10" },
  { verse: "Whatever you do, work at it with all your heart, as working for the Lord, not for human masters.", reference: "Colossians 3:23" },
  { verse: "A friend loves at all times, and a brother is born for a time of adversity.", reference: "Proverbs 17:17" },
  { verse: "With God all things are possible.", reference: "Matthew 19:26" },
  { verse: "Enter his gates with thanksgiving and his courts with praise; give thanks to him and praise his name.", reference: "Psalm 100:4" },
  { verse: "The heavens declare the glory of God; the skies proclaim the work of his hands.", reference: "Psalm 19:1" },
  { verse: "Be joyful in hope, patient in affliction, faithful in prayer.", reference: "Romans 12:12" },
  { verse: "How good and pleasant it is when God's people live together in unity!", reference: "Psalm 133:1" },
  { verse: "And let us consider how we may spur one another on toward love and good deeds.", reference: "Hebrews 10:24" },
  { verse: "Therefore encourage one another and build each other up, just as in fact you are doing.", reference: "1 Thessalonians 5:11" },
  { verse: "He makes me lie down in green pastures, he leads me beside quiet waters, he refreshes my soul.", reference: "Psalm 23:2-3" },
  { verse: "May the God of hope fill you with all joy and peace as you trust in him.", reference: "Romans 15:13" },
  { verse: "Taste and see that the LORD is good; blessed is the one who takes refuge in him.", reference: "Psalm 34:8" },
  { verse: "Great is our Lord and mighty in power; his understanding has no limit.", reference: "Psalm 147:5" },
  { verse: "The LORD is gracious and compassionate, slow to anger and rich in love.", reference: "Psalm 145:8" },
  { verse: "Commit to the LORD whatever you do, and he will establish your plans.", reference: "Proverbs 16:3" },
  { verse: "For we are God's handiwork, created in Christ Jesus to do good works, which God prepared in advance for us to do.", reference: "Ephesians 2:10" },
  { verse: "Give thanks to the LORD, for he is good; his love endures forever.", reference: "Psalm 107:1" },
  { verse: "I praise you because I am fearfully and wonderfully made; your works are wonderful, I know that full well.", reference: "Psalm 139:14" },
  { verse: "The LORD will fight for you; you need only to be still.", reference: "Exodus 14:14" },
  { verse: "Not by might nor by power, but by my Spirit, says the LORD Almighty.", reference: "Zechariah 4:6" },
  { verse: "Rejoice always, pray continually, give thanks in all circumstances; for this is God's will for you in Christ Jesus.", reference: "1 Thessalonians 5:16-18" },
  { verse: "God is our refuge and strength, an ever-present help in trouble.", reference: "Psalm 46:1" },
  { verse: "Blessed is the one who trusts in the LORD, whose confidence is in him.", reference: "Jeremiah 17:7" },
  { verse: "Let the peace of Christ rule in your hearts, since as members of one body you were called to peace.", reference: "Colossians 3:15" },
  { verse: "The earth is the LORD's, and everything in it, the world, and all who live in it.", reference: "Psalm 24:1" },
  { verse: "Love the LORD your God with all your heart and with all your soul and with all your strength.", reference: "Deuteronomy 6:5" },
  { verse: "Whoever dwells in the shelter of the Most High will rest in the shadow of the Almighty.", reference: "Psalm 91:1" },
  { verse: "But God demonstrates his own love for us in this: While we were still sinners, Christ died for us.", reference: "Romans 5:8" },
  { verse: "Ask and it will be given to you; seek and you will find; knock and the door will be opened to you.", reference: "Matthew 7:7" },
  { verse: "My grace is sufficient for you, for my power is made perfect in weakness.", reference: "2 Corinthians 12:9" },
  { verse: "Do not conform to the pattern of this world, but be transformed by the renewing of your mind.", reference: "Romans 12:2" },
  { verse: "Now faith is confidence in what we hope for and assurance about what we do not see.", reference: "Hebrews 11:1" },
  { verse: "The LORD makes firm the steps of the one who delights in him.", reference: "Psalm 37:23" },
  { verse: "He said to them, 'Go into all the world and preach the gospel to all creation.'", reference: "Mark 16:15" },
  { verse: "I have been crucified with Christ and I no longer live, but Christ lives in me.", reference: "Galatians 2:20" },
  { verse: "Brothers and sisters, I do not consider myself yet to have taken hold of it. But one thing I do: Forgetting what is behind and straining toward what is ahead.", reference: "Philippians 3:13" },
  { verse: "Let your light shine before others, that they may see your good deeds and glorify your Father in heaven.", reference: "Matthew 5:16" },
  { verse: "And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.", reference: "Philippians 4:7" },
  { verse: "Let everything that has breath praise the LORD.", reference: "Psalm 150:6" },
  { verse: "I am the vine; you are the branches. If you remain in me and I in you, you will bear much fruit.", reference: "John 15:5" },
  { verse: "There is a time for everything, and a season for every activity under the heavens.", reference: "Ecclesiastes 3:1" },
  { verse: "Be completely humble and gentle; be patient, bearing with one another in love.", reference: "Ephesians 4:2" },
  { verse: "The LORD is faithful to all his promises and loving toward all he has made.", reference: "Psalm 145:13" },
  { verse: "I lift up my eyes to the mountains—where does my help come from? My help comes from the LORD, the Maker of heaven and earth.", reference: "Psalm 121:1-2" },
  { verse: "We love because he first loved us.", reference: "1 John 4:19" },
  { verse: "Greater love has no one than this: to lay down one's life for one's friends.", reference: "John 15:13" },
  { verse: "Two are better than one, because they have a good return for their labor.", reference: "Ecclesiastes 4:9" },
  { verse: "Teach us to number our days, that we may gain a heart of wisdom.", reference: "Psalm 90:12" },
  { verse: "Set your minds on things above, not on earthly things.", reference: "Colossians 3:2" },
  { verse: "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable—if anything is excellent or praiseworthy—think about such things.", reference: "Philippians 4:8" },
  { verse: "The LORD is good, a refuge in times of trouble. He cares for those who trust in him.", reference: "Nahum 1:7" },
  { verse: "Humble yourselves before the Lord, and he will lift you up.", reference: "James 4:10" },
  { verse: "The righteous cry out, and the LORD hears them; he delivers them from all their troubles.", reference: "Psalm 34:17" },
  { verse: "Draw near to God, and he will draw near to you.", reference: "James 4:8" },
  { verse: "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God.", reference: "Romans 8:38-39" },
  { verse: "Jesus Christ is the same yesterday and today and forever.", reference: "Hebrews 13:8" },
  { verse: "You will keep in perfect peace those whose minds are steadfast, because they trust in you.", reference: "Isaiah 26:3" },
  { verse: "Because of the LORD's great love we are not consumed, for his compassions never fail.", reference: "Lamentations 3:22" },
  { verse: "Many are the plans in a person's heart, but it is the LORD's purpose that prevails.", reference: "Proverbs 19:21" },
  { verse: "The LORD is compassionate and gracious, slow to anger, abounding in love.", reference: "Psalm 103:8" },
  { verse: "Be still before the LORD and wait patiently for him.", reference: "Psalm 37:7" },
  { verse: "Weeping may stay for the night, but rejoicing comes in the morning.", reference: "Psalm 30:5" },
  { verse: "For nothing will be impossible with God.", reference: "Luke 1:37" },
  { verse: "O LORD, you are my God; I will exalt you and praise your name, for in perfect faithfulness you have done wonderful things.", reference: "Isaiah 25:1" },
  { verse: "Let us run with perseverance the race marked out for us, fixing our eyes on Jesus.", reference: "Hebrews 12:1-2" },
  { verse: "All Scripture is God-breathed and is useful for teaching, rebuking, correcting and training in righteousness.", reference: "2 Timothy 3:16" },
  { verse: "Put on the full armor of God, so that you can take your stand against the devil's schemes.", reference: "Ephesians 6:11" },
  { verse: "Whoever sows generously will also reap generously.", reference: "2 Corinthians 9:6" },
  { verse: "Train up a child in the way he should go; even when he is old he will not depart from it.", reference: "Proverbs 22:6" },
  { verse: "Seek the LORD while he may be found; call on him while he is near.", reference: "Isaiah 55:6" },
  { verse: "But the Lord is faithful, and he will strengthen you and protect you from the evil one.", reference: "2 Thessalonians 3:3" },
  { verse: "Bless those who persecute you; bless and do not curse.", reference: "Romans 12:14" },
  { verse: "He has shown you, O mortal, what is good. And what does the LORD require of you? To act justly and to love mercy and to walk humbly with your God.", reference: "Micah 6:8" },
  { verse: "The fear of the LORD is the beginning of wisdom, and knowledge of the Holy One is understanding.", reference: "Proverbs 9:10" },
  { verse: "I will praise you, LORD, with all my heart; I will tell of all your wonderful deeds.", reference: "Psalm 9:1" },
  { verse: "The LORD is near to all who call on him, to all who call on him in truth.", reference: "Psalm 145:18" },
  { verse: "Blessed are those who hunger and thirst for righteousness, for they will be filled.", reference: "Matthew 5:6" },
  { verse: "For we walk by faith, not by sight.", reference: "2 Corinthians 5:7" },
  { verse: "The light shines in the darkness, and the darkness has not overcome it.", reference: "John 1:5" },
  { verse: "Therefore, since we are surrounded by such a great cloud of witnesses, let us throw off everything that hinders and the sin that so easily entangles.", reference: "Hebrews 12:1" },
  { verse: "If we confess our sins, he is faithful and just and will forgive us our sins and purify us from all unrighteousness.", reference: "1 John 1:9" },
  { verse: "For the LORD gives wisdom; from his mouth come knowledge and understanding.", reference: "Proverbs 2:6" },
  { verse: "The LORD is my strength and my shield; my heart trusts in him, and he helps me.", reference: "Psalm 28:7" },
  { verse: "Children, obey your parents in the Lord, for this is right.", reference: "Ephesians 6:1" },
  { verse: "I have hidden your word in my heart that I might not sin against you.", reference: "Psalm 119:11" },
  { verse: "So whether you eat or drink or whatever you do, do it all for the glory of God.", reference: "1 Corinthians 10:31" },
  { verse: "God is love. Whoever lives in love lives in God, and God in them.", reference: "1 John 4:16" },
  { verse: "My soul finds rest in God alone; my salvation comes from him.", reference: "Psalm 62:1" },
  { verse: "Cast your cares on the LORD and he will sustain you; he will never let the righteous be shaken.", reference: "Psalm 55:22" },
  { verse: "I am the good shepherd. The good shepherd lays down his life for the sheep.", reference: "John 10:11" },
  { verse: "May the words of my mouth and this meditation of my heart be pleasing in your sight, LORD, my Rock and my Redeemer.", reference: "Psalm 19:14" },
  { verse: "Surely goodness and love will follow me all the days of my life, and I will dwell in the house of the LORD forever.", reference: "Psalm 23:6" },
  { verse: "Let the morning bring me word of your unfailing love, for I have put my trust in you.", reference: "Psalm 143:8" },
  { verse: "For where your treasure is, there your heart will be also.", reference: "Matthew 6:21" },
  { verse: "I press on toward the goal to win the prize for which God has called me heavenward in Christ Jesus.", reference: "Philippians 3:14" },
  { verse: "And my God will meet all your needs according to the riches of his glory in Christ Jesus.", reference: "Philippians 4:19" },
  { verse: "In him we have redemption through his blood, the forgiveness of sins, in accordance with the riches of God's grace.", reference: "Ephesians 1:7" },
  { verse: "Blessed is the man who remains steadfast under trial, for when he has stood the test he will receive the crown of life.", reference: "James 1:12" },
  { verse: "The LORD will guide you always; he will satisfy your needs in a sun-scorched land.", reference: "Isaiah 58:11" },
  { verse: "But thanks be to God! He gives us the victory through our Lord Jesus Christ.", reference: "1 Corinthians 15:57" },
  { verse: "I have set the LORD always before me. Because he is at my right hand, I will not be shaken.", reference: "Psalm 16:8" },
  { verse: "O give thanks unto the LORD, for he is good: for his mercy endureth for ever.", reference: "Psalm 136:1" },
  { verse: "Trust in him at all times, you people; pour out your hearts to him, for God is our refuge.", reference: "Psalm 62:8" },
  { verse: "Do not let any unwholesome talk come out of your mouths, but only what is helpful for building others up according to their needs.", reference: "Ephesians 4:29" },
  { verse: "From the rising of the sun to the place where it sets, the name of the LORD is to be praised.", reference: "Psalm 113:3" },
  { verse: "Have mercy on me, O God, according to your unfailing love; according to your great compassion blot out my transgressions.", reference: "Psalm 51:1" },
  { verse: "Know that the LORD is God. It is he who made us, and we are his; we are his people, the sheep of his pasture.", reference: "Psalm 100:3" },
  { verse: "Those who sow with tears will reap with songs of joy.", reference: "Psalm 126:5" },
  { verse: "The LORD has done great things for us, and we are filled with joy.", reference: "Psalm 126:3" },
  { verse: "Devote yourselves to prayer, being watchful and thankful.", reference: "Colossians 4:2" },
  { verse: "The LORD watches over all who love him.", reference: "Psalm 145:20" },
  { verse: "I will give you a new heart and put a new spirit in you.", reference: "Ezekiel 36:26" },
  { verse: "You make known to me the path of life; you will fill me with joy in your presence.", reference: "Psalm 16:11" },
  { verse: "And whatever you do, whether in word or deed, do it all in the name of the Lord Jesus, giving thanks to God the Father through him.", reference: "Colossians 3:17" },
  { verse: "He is before all things, and in him all things hold together.", reference: "Colossians 1:17" },
  { verse: "Show me your ways, LORD, teach me your paths.", reference: "Psalm 25:4" },
  { verse: "But grow in the grace and knowledge of our Lord and Savior Jesus Christ.", reference: "2 Peter 3:18" },
  { verse: "Keep your lives free from the love of money and be content with what you have, because God has said, 'Never will I leave you; never will I forsake you.'", reference: "Hebrews 13:5" },
  { verse: "Praise the LORD, my soul; all my inmost being, praise his holy name.", reference: "Psalm 103:1" },
  { verse: "Grace and peace to you from God our Father and from the Lord Jesus Christ.", reference: "Philippians 1:2" },
  { verse: "Forget the former things; do not dwell on the past. See, I am doing a new thing!", reference: "Isaiah 43:18-19" },
  { verse: "A gentle answer turns away wrath, but a harsh word stirs up anger.", reference: "Proverbs 15:1" },
  { verse: "Charm is deceptive, and beauty is fleeting; but a woman who fears the LORD is to be praised.", reference: "Proverbs 31:30" },
  { verse: "If any of you lacks wisdom, you should ask God, who gives generously to all without finding fault, and it will be given to you.", reference: "James 1:5" },
  { verse: "The LORD is my strength and my song; he has become my salvation.", reference: "Exodus 15:2" },
  { verse: "I am the Alpha and the Omega, the First and the Last, the Beginning and the End.", reference: "Revelation 22:13" },
  { verse: "Remain in me, as I also remain in you. No branch can bear fruit by itself; it must remain in the vine.", reference: "John 15:4" },
  { verse: "He who is in you is greater than he who is in the world.", reference: "1 John 4:4" },
  { verse: "Therefore, go and make disciples of all nations.", reference: "Matthew 28:19" },
  { verse: "For I am the LORD your God who takes hold of your right hand and says to you, Do not fear; I will help you.", reference: "Isaiah 41:13" },
  { verse: "The LORD is my portion; therefore I will wait for him.", reference: "Lamentations 3:24" },
  { verse: "The Lord is not slow in keeping his promise, as some understand slowness. Instead he is patient with you.", reference: "2 Peter 3:9" },
  { verse: "Blessed are the pure in heart, for they will see God.", reference: "Matthew 5:8" },
  { verse: "And surely I am with you always, to the very end of the age.", reference: "Matthew 28:20" },
  { verse: "Clap your hands, all you nations; shout to God with cries of joy.", reference: "Psalm 47:1" },
  { verse: "My flesh and my heart may fail, but God is the strength of my heart and my portion forever.", reference: "Psalm 73:26" },
  { verse: "But you, LORD, are a shield around me, my glory, the One who lifts my head high.", reference: "Psalm 3:3" },
  { verse: "Whoever believes in me, as Scripture has said, rivers of living water will flow from within them.", reference: "John 7:38" },
  { verse: "Bear with each other and forgive one another if any of you has a grievance against someone.", reference: "Colossians 3:13" },
  { verse: "How precious to me are your thoughts, God! How vast is the sum of them!", reference: "Psalm 139:17" },
  { verse: "The Lord will rescue me from every evil attack and will bring me safely to his heavenly kingdom.", reference: "2 Timothy 4:18" },
  { verse: "Thanks be to God for his indescribable gift!", reference: "2 Corinthians 9:15" },
  { verse: "He restores my soul. He guides me along the right paths for his name's sake.", reference: "Psalm 23:3" },
  { verse: "Search me, God, and know my heart; test me and know my anxious thoughts.", reference: "Psalm 139:23" },
  { verse: "I will lie down and sleep in peace, for you alone, LORD, make me dwell in safety.", reference: "Psalm 4:8" },
  { verse: "The Lord is my helper; I will not be afraid. What can mere mortals do to me?", reference: "Hebrews 13:6" },
  { verse: "Then you will call on me and come and pray to me, and I will listen to you.", reference: "Jeremiah 29:12" },
  { verse: "Blessed are the meek, for they will inherit the earth.", reference: "Matthew 5:5" },
  { verse: "The fear of the LORD is the beginning of knowledge, but fools despise wisdom and instruction.", reference: "Proverbs 1:7" },
  { verse: "Who shall separate us from the love of Christ? Shall trouble or hardship or persecution or famine or nakedness or danger or sword?", reference: "Romans 8:35" },
  { verse: "Be on your guard; stand firm in the faith; be courageous; be strong.", reference: "1 Corinthians 16:13" },
  { verse: "The LORD is a refuge for the oppressed, a stronghold in times of trouble.", reference: "Psalm 9:9" },
  { verse: "For the word of God is alive and active. Sharper than any double-edged sword.", reference: "Hebrews 4:12" },
  { verse: "The thief comes only to steal and kill and destroy; I have come that they may have life, and have it to the full.", reference: "John 10:10" },
  { verse: "Therefore do not worry about tomorrow, for tomorrow will worry about itself.", reference: "Matthew 6:34" },
  { verse: "The LORD has made his salvation known and revealed his righteousness to the nations.", reference: "Psalm 98:2" },
  { verse: "Submit yourselves, then, to God. Resist the devil, and he will flee from you.", reference: "James 4:7" },
  { verse: "So we fix our eyes not on what is seen, but on what is unseen, since what is seen is temporary, but what is unseen is eternal.", reference: "2 Corinthians 4:18" },
  { verse: "The Lord your God is gracious and merciful and will not turn his face from you if you return to him.", reference: "2 Chronicles 30:9" },
  { verse: "And God is able to bless you abundantly, so that in all things at all times, having all that you need, you will abound in every good work.", reference: "2 Corinthians 9:8" },
  { verse: "Do not be overcome by evil, but overcome evil with good.", reference: "Romans 12:21" },
  { verse: "For the LORD God is a sun and shield; the LORD bestows favor and honor.", reference: "Psalm 84:11" },
  { verse: "How great you are, Sovereign LORD! There is no one like you, and there is no God but you.", reference: "2 Samuel 7:22" },
  { verse: "The Spirit of the Lord is on me, because he has anointed me to proclaim good news to the poor.", reference: "Luke 4:18" },
  { verse: "Be merciful, just as your Father is merciful.", reference: "Luke 6:36" },
  { verse: "One thing I ask from the LORD, this only do I seek: that I may dwell in the house of the LORD all the days of my life.", reference: "Psalm 27:4" },
  { verse: "But the wisdom that comes from heaven is first of all pure; then peace-loving, considerate, submissive, full of mercy and good fruit.", reference: "James 3:17" },
  { verse: "Therefore, since we have been justified through faith, we have peace with God through our Lord Jesus Christ.", reference: "Romans 5:1" },
  { verse: "Sing to the LORD a new song, for he has done marvelous things.", reference: "Psalm 98:1" },
  { verse: "For the Son of Man came to seek and to save the lost.", reference: "Luke 19:10" },
  { verse: "Be strong in the Lord and in his mighty power.", reference: "Ephesians 6:10" },
  { verse: "Whoever is kind to the poor lends to the LORD, and he will reward them for what they have done.", reference: "Proverbs 19:17" },
  { verse: "The LORD is my strength and my defense; he has become my salvation.", reference: "Psalm 118:14" },
  { verse: "Yet to all who did receive him, to those who believed in his name, he gave the right to become children of God.", reference: "John 1:12" },
  { verse: "Do to others as you would have them do to you.", reference: "Luke 6:31" },
  { verse: "But you are a chosen people, a royal priesthood, a holy nation, God's special possession.", reference: "1 Peter 2:9" },
  { verse: "The heavens declare the glory of God; the skies proclaim the work of his hands. Day after day they pour forth speech.", reference: "Psalm 19:1-2" },
  { verse: "Love your neighbor as yourself.", reference: "Mark 12:31" },
  { verse: "But the Lord stood at my side and gave me strength.", reference: "2 Timothy 4:17" },
  { verse: "He will cover you with his feathers, and under his wings you will find refuge.", reference: "Psalm 91:4" },
  { verse: "The LORD reigns, let the earth be glad; let the distant shores rejoice.", reference: "Psalm 97:1" },
  { verse: "Rejoice in the Lord always. I will say it again: Rejoice!", reference: "Philippians 4:4" },
  { verse: "Therefore, as God's chosen people, holy and dearly loved, clothe yourselves with compassion, kindness, humility, gentleness and patience.", reference: "Colossians 3:12" },
  { verse: "The LORD gives strength to his people; the LORD blesses his people with peace.", reference: "Psalm 29:11" },
  { verse: "Whoever finds their life will lose it, and whoever loses their life for my sake will find it.", reference: "Matthew 10:39" },
  { verse: "By wisdom a house is built, and through understanding it is established.", reference: "Proverbs 24:3" },
  { verse: "Let love and faithfulness never leave you; bind them around your neck, write them on the tablet of your heart.", reference: "Proverbs 3:3" },
  { verse: "My sheep listen to my voice; I know them, and they follow me.", reference: "John 10:27" },
  { verse: "For the LORD is good and his love endures forever; his faithfulness continues through all generations.", reference: "Psalm 100:5" },
  { verse: "The LORD is slow to anger and great in power.", reference: "Nahum 1:3" },
  { verse: "Arise, shine, for your light has come, and the glory of the LORD rises upon you.", reference: "Isaiah 60:1" },
  { verse: "Blessed are those who mourn, for they will be comforted.", reference: "Matthew 5:4" },
  { verse: "And without faith it is impossible to please God, because anyone who comes to him must believe that he exists and that he rewards those who earnestly seek him.", reference: "Hebrews 11:6" },
  { verse: "Be devoted to one another in love. Honor one another above yourselves.", reference: "Romans 12:10" },
  { verse: "He has made us competent as ministers of a new covenant—not of the letter but of the Spirit.", reference: "2 Corinthians 3:6" },
  { verse: "Blessed is the nation whose God is the LORD, the people he chose for his inheritance.", reference: "Psalm 33:12" },
  { verse: "Therefore confess your sins to each other and pray for each other so that you may be healed.", reference: "James 5:16" },
  { verse: "I waited patiently for the LORD; he turned to me and heard my cry.", reference: "Psalm 40:1" },
  { verse: "How great is your goodness, which you have stored up for those who fear you.", reference: "Psalm 31:19" },
  { verse: "For you created my inmost being; you knit me together in my mother's womb.", reference: "Psalm 139:13" },
  { verse: "Everyone who calls on the name of the Lord will be saved.", reference: "Romans 10:13" },
  { verse: "The LORD is righteous in all his ways and faithful in all he does.", reference: "Psalm 145:17" },
  { verse: "Come, let us sing for joy to the LORD; let us shout aloud to the Rock of our salvation.", reference: "Psalm 95:1" },
  { verse: "Give, and it will be given to you. A good measure, pressed down, shaken together and running over.", reference: "Luke 6:38" },
  { verse: "Truly he is my rock and my salvation; he is my fortress, I will never be shaken.", reference: "Psalm 62:2" },
  { verse: "Salvation belongs to the LORD; your blessing be on your people!", reference: "Psalm 3:8" },
  { verse: "The Lord is my rock, my fortress and my deliverer.", reference: "2 Samuel 22:2" },
  { verse: "Blessed is the one whose transgressions are forgiven, whose sins are covered.", reference: "Psalm 32:1" },
  { verse: "The LORD is exalted over all the nations, his glory above the heavens.", reference: "Psalm 113:4" },
  { verse: "Walk in obedience to all that the LORD your God has commanded you, so that you may live and prosper.", reference: "Deuteronomy 5:33" },
  { verse: "The Lord is near. Do not be anxious about anything.", reference: "Philippians 4:5-6" },
  { verse: "You are my hiding place; you will protect me from trouble and surround me with songs of deliverance.", reference: "Psalm 32:7" },
  { verse: "Dear friends, let us love one another, for love comes from God.", reference: "1 John 4:7" },
  { verse: "When I am afraid, I put my trust in you.", reference: "Psalm 56:3" },
  { verse: "The God of all grace, who called you to his eternal glory in Christ, after you have suffered a little while, will himself restore you and make you strong.", reference: "1 Peter 5:10" },
  { verse: "How sweet are your words to my taste, sweeter than honey to my mouth!", reference: "Psalm 119:103" },
  { verse: "Shout for joy to the LORD, all the earth.", reference: "Psalm 100:1" },
  { verse: "In repentance and rest is your salvation, in quietness and trust is your strength.", reference: "Isaiah 30:15" },
  { verse: "The LORD is King for ever and ever.", reference: "Psalm 10:16" },
  { verse: "If you remain in me and my words remain in you, ask whatever you wish, and it will be done for you.", reference: "John 15:7" },
  { verse: "For you have been my refuge, a strong tower against the foe.", reference: "Psalm 61:3" },
  { verse: "For the grace of God has appeared that offers salvation to all people.", reference: "Titus 2:11" },
  { verse: "O LORD my God, I called to you for help, and you healed me.", reference: "Psalm 30:2" },
  { verse: "The eyes of the LORD are on the righteous, and his ears are attentive to their cry.", reference: "Psalm 34:15" },
  { verse: "He who did not spare his own Son, but gave him up for us all—how will he not also, along with him, graciously give us all things?", reference: "Romans 8:32" },
  { verse: "Praise be to the God and Father of our Lord Jesus Christ, who has blessed us in the heavenly realms with every spiritual blessing in Christ.", reference: "Ephesians 1:3" },
  { verse: "Whoever has the Son has life; whoever does not have the Son of God does not have life.", reference: "1 John 5:12" },
  { verse: "The righteous person may have many troubles, but the LORD delivers him from them all.", reference: "Psalm 34:19" },
  { verse: "He has removed our sins as far from us as the east is from the west.", reference: "Psalm 103:12" },
  { verse: "For the kingdom of God is not a matter of eating and drinking, but of righteousness, peace and joy in the Holy Spirit.", reference: "Romans 14:17" },
  { verse: "I will be glad and rejoice in your love, for you saw my affliction and knew the anguish of my soul.", reference: "Psalm 31:7" },
  { verse: "A new command I give you: Love one another. As I have loved you, so you must love one another.", reference: "John 13:34" },
  { verse: "But the plans of the LORD stand firm forever, the purposes of his heart through all generations.", reference: "Psalm 33:11" },
  { verse: "The Spirit himself testifies with our spirit that we are God's children.", reference: "Romans 8:16" },
  { verse: "Come to me, all who labor and are heavy laden, and I will give you rest. Take my yoke upon you and learn from me.", reference: "Matthew 11:28-29" },
  { verse: "Praise the LORD, my soul, and forget not all his benefits.", reference: "Psalm 103:2" },
  { verse: "Stand firm then, with the belt of truth buckled around your waist, with the breastplate of righteousness in place.", reference: "Ephesians 6:14" },
  { verse: "Have you not known? Have you not heard? The LORD is the everlasting God, the Creator of the ends of the earth.", reference: "Isaiah 40:28" },
  { verse: "Therefore, my dear brothers and sisters, stand firm. Let nothing move you. Always give yourselves fully to the work of the Lord.", reference: "1 Corinthians 15:58" },
  { verse: "Heal me, LORD, and I will be healed; save me and I will be saved, for you are the one I praise.", reference: "Jeremiah 17:14" },
  { verse: "Oh, the depth of the riches of the wisdom and knowledge of God! How unsearchable his judgments, and his paths beyond tracing out!", reference: "Romans 11:33" },
  { verse: "How beautiful on the mountains are the feet of those who bring good news.", reference: "Isaiah 52:7" },
  { verse: "Surely God is my salvation; I will trust and not be afraid.", reference: "Isaiah 12:2" },
  { verse: "The LORD your God will bless you in all your harvest and in all the work of your hands, and your joy will be complete.", reference: "Deuteronomy 16:15" },
  { verse: "No temptation has overtaken you except what is common to mankind. And God is faithful; he will not let you be tempted beyond what you can bear.", reference: "1 Corinthians 10:13" },
  { verse: "I will sing to the LORD all my life; I will sing praise to my God as long as I live.", reference: "Psalm 104:33" },
  { verse: "Now to him who is able to do immeasurably more than all we ask or imagine, according to his power that is at work within us.", reference: "Ephesians 3:20" },
  { verse: "For you were once darkness, but now you are light in the Lord. Live as children of light.", reference: "Ephesians 5:8" },
  { verse: "But as for me, I watch in hope for the LORD, I wait for God my Savior; my God will hear me.", reference: "Micah 7:7" },
  { verse: "For the message of the cross is foolishness to those who are perishing, but to us who are being saved it is the power of God.", reference: "1 Corinthians 1:18" },
  { verse: "The LORD your God has blessed you in all the work of your hands.", reference: "Deuteronomy 2:7" },
  { verse: "And over all these virtues put on love, which binds them all together in perfect unity.", reference: "Colossians 3:14" },
  { verse: "The righteous will flourish like a palm tree, they will grow like a cedar of Lebanon.", reference: "Psalm 92:12" },
  { verse: "So in Christ Jesus you are all children of God through faith.", reference: "Galatians 3:26" },
  { verse: "For the word of the LORD is right and true; he is faithful in all he does.", reference: "Psalm 33:4" },
  { verse: "Therefore I tell you, whatever you ask for in prayer, believe that you have received it, and it will be yours.", reference: "Mark 11:24" },
  { verse: "I know that my redeemer lives, and that in the end he will stand on the earth.", reference: "Job 19:25" },
  { verse: "Sing to the LORD, praise his name; proclaim his salvation day after day.", reference: "Psalm 96:2" },
  { verse: "He tends his flock like a shepherd: He gathers the lambs in his arms and carries them close to his heart.", reference: "Isaiah 40:11" },
  { verse: "Do not merely listen to the word, and so deceive yourselves. Do what it says.", reference: "James 1:22" },
  { verse: "But you, Lord, are a compassionate and gracious God, slow to anger, abounding in love and faithfulness.", reference: "Psalm 86:15" },
  { verse: "For the Lord your God is God of gods and Lord of lords, the great God, mighty and awesome.", reference: "Deuteronomy 10:17" },
  { verse: "The LORD God is my strength; he makes my feet like the feet of a deer and enables me to tread on the heights.", reference: "Habakkuk 3:19" },
  { verse: "We are more than conquerors through him who loved us.", reference: "Romans 8:37" },
  { verse: "O Lord, hear my prayer, listen to my cry for mercy; in your faithfulness and righteousness come to my relief.", reference: "Psalm 143:1" },
  { verse: "The Lord bless you and keep you; the Lord make his face to shine upon you and be gracious to you.", reference: "Numbers 6:24-26" },
  { verse: "Therefore, there is now no condemnation for those who are in Christ Jesus.", reference: "Romans 8:1" },
  { verse: "If my people, who are called by my name, will humble themselves and pray and seek my face and turn from their wicked ways, then I will hear from heaven.", reference: "2 Chronicles 7:14" },
  { verse: "For we know that if the earthly tent we live in is destroyed, we have a building from God, an eternal house in heaven.", reference: "2 Corinthians 5:1" },
  { verse: "Blessed be the God and Father of our Lord Jesus Christ! According to his great mercy, he has caused us to be born again to a living hope.", reference: "1 Peter 1:3" },
  { verse: "The LORD will fulfill his purpose for me; your steadfast love, O LORD, endures forever.", reference: "Psalm 138:8" },
  { verse: "Look to the LORD and his strength; seek his face always.", reference: "1 Chronicles 16:11" },
  { verse: "My help comes from the LORD, the Maker of heaven and earth.", reference: "Psalm 121:2" },
  { verse: "Let the word of Christ dwell in you richly, teaching and admonishing one another in all wisdom.", reference: "Colossians 3:16" },
  { verse: "The LORD is on my side; I will not fear. What can man do to me?", reference: "Psalm 118:6" },
  { verse: "If we live, we live for the Lord; and if we die, we die for the Lord. So, whether we live or die, we belong to the Lord.", reference: "Romans 14:8" },
  { verse: "For the eyes of the Lord are on the righteous and his ears are attentive to their prayer.", reference: "1 Peter 3:12" },
  { verse: "Great peace have those who love your law, and nothing can make them stumble.", reference: "Psalm 119:165" },
  { verse: "Whoever wants to be my disciple must deny themselves and take up their cross and follow me.", reference: "Matthew 16:24" },
  { verse: "The light of the righteous shines brightly, but the lamp of the wicked is snuffed out.", reference: "Proverbs 13:9" },
  { verse: "For the LORD takes delight in his people; he crowns the humble with victory.", reference: "Psalm 149:4" },
  { verse: "God opposes the proud but shows favor to the humble.", reference: "James 4:6" },
  { verse: "I am with you and will watch over you wherever you go.", reference: "Genesis 28:15" },
  { verse: "May he give you the desire of your heart and make all your plans succeed.", reference: "Psalm 20:4" },
  { verse: "The earth is full of the goodness of the LORD.", reference: "Psalm 33:5" },
  { verse: "Hear, O Israel: The LORD our God, the LORD is one.", reference: "Deuteronomy 6:4" },
  { verse: "Though the mountains be shaken and the hills be removed, yet my unfailing love for you will not be shaken.", reference: "Isaiah 54:10" },
  { verse: "He will wipe every tear from their eyes. There will be no more death or mourning or crying or pain.", reference: "Revelation 21:4" },
  { verse: "I have fought the good fight, I have finished the race, I have kept the faith.", reference: "2 Timothy 4:7" },
  { verse: "The heavens are yours, and yours also the earth; you founded the world and all that is in it.", reference: "Psalm 89:11" },
  { verse: "Oh, how I love your law! I meditate on it all day long.", reference: "Psalm 119:97" },
  { verse: "My God, my God, why have you forsaken me? Why are you so far from saving me?", reference: "Psalm 22:1" },
  { verse: "Before I formed you in the womb I knew you, before you were born I set you apart.", reference: "Jeremiah 1:5" },
  { verse: "He who finds a wife finds what is good and receives favor from the LORD.", reference: "Proverbs 18:22" },
  { verse: "Behold, I stand at the door and knock. If anyone hears my voice and opens the door, I will come in.", reference: "Revelation 3:20" },
  { verse: "The stone the builders rejected has become the cornerstone.", reference: "Psalm 118:22" },
  { verse: "Now the Lord is the Spirit, and where the Spirit of the Lord is, there is freedom.", reference: "2 Corinthians 3:17" },
  { verse: "He makes wars cease to the ends of the earth. He breaks the bow and shatters the spear.", reference: "Psalm 46:9" },
  { verse: "For he chose us in him before the creation of the world to be holy and blameless in his sight.", reference: "Ephesians 1:4" },
  { verse: "I will give them a heart to know me, that I am the LORD.", reference: "Jeremiah 24:7" },
  { verse: "But those who suffer he delivers in their suffering; he speaks to them in their affliction.", reference: "Job 36:15" },
  { verse: "Wait for the LORD and keep his way. He will exalt you to inherit the land.", reference: "Psalm 37:34" },
  { verse: "The LORD will keep you from all harm—he will watch over your life.", reference: "Psalm 121:7" },
  { verse: "The LORD reigns forever; he has established his throne for judgment.", reference: "Psalm 9:7" },
];

export function getWordOfTheDay(): { verse: string; reference: string } {
  const now = new Date();
  const hours = now.getHours();

  const effectiveDate = new Date(now);
  if (hours < 7) {
    effectiveDate.setDate(effectiveDate.getDate() - 1);
  }

  const startOfYear = new Date(effectiveDate.getFullYear(), 0, 0);
  const diff = effectiveDate.getTime() - startOfYear.getTime();
  const dayOfYear = Math.floor(diff / (1000 * 60 * 60 * 24));

  const index = dayOfYear % BIBLE_VERSES.length;
  return BIBLE_VERSES[index];
}

export function getNextResetTime(): Date {
  const now = new Date();
  const reset = new Date(now);
  reset.setHours(7, 0, 0, 0);

  if (now >= reset) {
    reset.setDate(reset.getDate() + 1);
  }

  return reset;
}

export function getTimeUntilReset(): string {
  const now = new Date();
  const reset = getNextResetTime();
  const diff = reset.getTime() - now.getTime();

  const hours = Math.floor(diff / (1000 * 60 * 60));
  const minutes = Math.floor((diff % (1000 * 60 * 60)) / (1000 * 60));

  if (hours > 0) {
    return `${hours}h ${minutes}m`;
  }
  return `${minutes}m`;
}
