workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      groups:
        - app_credentials
      vars:
        PACKAGE_NAME: "com.christcollective.app"
      node: 20.11.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - user@example.com
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true

  ios-workflow:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: codemagic
    environment:
      ios_signing:
        distribution_type: ad_hoc
        bundle_identifier: com.christcollective.app
      groups:
        - app_credentials
      vars:
        BUNDLE_ID: "com.christcollective.app"
        XCODE_WORKSPACE: "App.xcworkspace"
        XCODE_SCHEME: "App"
      node: 20.11.0
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync ios
      - name: Install CocoaPods dependencies
        script: |
          cd ios/App
          pod install
      - name: Build iOS
        script: |
          cd ios
          xcodebuild -workspace App.xcworkspace \
            -scheme App \
            -configuration Release \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            clean archive
      - name: Export IPA
        script: |
          xcodebuild -exportArchive \
            -archivePath $CM_BUILD_DIR/App.xcarchive \
            -exportPath $CM_BUILD_DIR \
            -exportOptionsPlist ios/exportOptions.plist
    artifacts:
      - $CM_BUILD_DIR/*.ipa
    publishing:
      email:
        recipients:
          - user@example.com
      app_store_connect:
        auth: integration
        submit_to_testflight: true
