workflows:
  ionic-capacitor:
    name: Build Ionic Capacitor app (iOS Simulator)
    max_build_duration: 60
    instance_type: mac_mini_m2

    environment:
      vars:
        NODE_VERSION: 18
        VITE_API_URL: https://f854b4eb-c67e-4b56-9fcf-97d9ce2c746c-00-e7qm2jhf778p.picard.replit.dev
      flutter: stable
      xcode: latest

    scripts:
      - name: Install dependencies
        script: |
          npm ci

      - name: Build web assets
        script: |
          npm run build

      - name: Sync Capacitor
        script: |
          npx cap sync ios

      - name: Build iOS simulator app
        script: |
          cd ios/App
          xcodebuild clean
          xcodebuild \
            -workspace App.xcworkspace \
            -scheme App \
            -configuration Debug \
            -sdk iphonesimulator \
            -derivedDataPath ../../ios-build

    artifacts:
      - ios-build/Build/Products/Debug-iphonesimulator/*.app

    publishing:
      email:
        recipients:
          - christcollective369@gmail.com

  android-workflow:
    name: Android Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      android_signing:
        - keystore_reference
      vars:
        PACKAGE_NAME: "com.christcollective.app"
      node: 20.11.0
    scripts:
      - name: Install dependencies
        script: |
          npm install
      - name: Build web assets
        script: |
          npm run build
      - name: Sync Capacitor
        script: |
          npx cap sync android
      - name: Build Android APK
        script: |
          cd android
          ./gradlew assembleRelease
    artifacts:
      - android/app/build/outputs/**/*.apk
      - android/app/build/outputs/**/mapping.txt
    publishing:
      email:
        recipients:
          - christcollective369@gmail.com
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: internal
        submit_as_draft: true
